# Generated by Django 6.0 on 2025-12-18 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animal', '0001_initial'),
        ('employee', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyType',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        max_length=100, verbose_name='Type de rendez-vous'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Type de rendez-vous',
                'verbose_name_plural': 'Types de rendez-vous',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(max_length=50, verbose_name="Nom de l'équipement"),
                ),
            ],
            options={
                'verbose_name': 'Équipement',
                'verbose_name_plural': 'Équipements',
            },
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        max_length=100, verbose_name='Nom de la procédure'
                    ),
                ),
                (
                    'price',
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name='Prix (CHF)'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Procédure',
                'verbose_name_plural': 'Procédures',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Salles',
                'verbose_name_plural': 'Salles',
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=50, verbose_name='Type de salle')),
            ],
            options={
                'verbose_name': 'Type de salle',
                'verbose_name_plural': 'Types de salle',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                (
                    'animal',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='appointment',
                        to='animal.animal',
                        verbose_name='Animal',
                    ),
                ),
                (
                    'employee',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='appointment',
                        to='employee.employee',
                        verbose_name='Employé',
                    ),
                ),
                (
                    'emergency_type',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='appointment',
                        to='appointment.emergencytype',
                        verbose_name='Type de consultation',
                    ),
                ),
                (
                    'room',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='appointment',
                        to='appointment.room',
                        verbose_name='Salle',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Consultation',
                'verbose_name_plural': 'Consultations',
            },
        ),
        migrations.CreateModel(
            name='AppointmentItem',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('quantity', models.IntegerField()),
                (
                    'appointment',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to='appointment.appointment',
                        verbose_name='Consultation',
                    ),
                ),
                (
                    'item',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to='inventory.item',
                        verbose_name='Article',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Association consultation/article',
                'verbose_name_plural': 'Associations consultation/article',
            },
        ),
        migrations.CreateModel(
            name='AppointmentProcedure',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('quantity', models.IntegerField()),
                (
                    'appointment',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to='appointment.appointment',
                        verbose_name='Consultation',
                    ),
                ),
                (
                    'procedure',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to='appointment.procedure',
                        verbose_name='Procédure',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Association consultation/procédure',
                'verbose_name_plural': 'Associations consultation/procédure',
            },
        ),
        migrations.CreateModel(
            name='AppointmentEquipment',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'appointment',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to='appointment.appointment',
                        verbose_name='Consultation',
                    ),
                ),
                (
                    'equipment',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to='appointment.procedure',
                        verbose_name='Équipement',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Association consultation/équipement',
                'verbose_name_plural': 'Associations consultation/équipement',
            },
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='room',
                to='appointment.roomtype',
                verbose_name='Type de salle',
            ),
        ),
    ]
