# Generated by Django 6.0 on 2025-12-18 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentequipment',
            name='equipment',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to='appointment.equipment',
                verbose_name='Équipement',
            ),
        ),
    ]
