# Generated by Django 6.0 on 2026-01-09 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='creation_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
