# Generated by Django 5.1.14 on 2025-12-11 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name="Nom de l'article")),
                ('reminder', models.BooleanField(default=False, verbose_name='Rappel nécessaire')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix (CHF)')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TreatmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, verbose_name='Type de traitement')),
            ],
            options={
                'verbose_name': 'Type de traitement',
                'verbose_name_plural': 'Types de traitements',
                'ordering': ['type'],
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='Quantité en stock')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_records', to='inventory.item', verbose_name='Article')),
            ],
            options={
                'verbose_name': 'Inventaire',
                'verbose_name_plural': 'Inventaires',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='treatment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='inventory.treatmenttype', verbose_name='Type de traitement'),
        ),
    ]
