# Generated by Django 6.0 on 2025-12-16 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointementEquipement',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Association consultation/équipement',
                'verbose_name_plural': 'Associations consultation/équipement',
            },
        ),
        migrations.CreateModel(
            name='AppointementProcedure',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('quantity', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Association consultation/procédure',
                'verbose_name_plural': 'Associations consultation/procédure',
            },
        ),
        migrations.CreateModel(
            name='EmergencyType',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        max_length=100, verbose_name='Type de rendez-vous'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Type de rendez-vous',
                'verbose_name_plural': 'Types de rendez-vous',
            },
        ),
        migrations.CreateModel(
            name='Equipement',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(max_length=50, verbose_name="Nom de l'équipement"),
                ),
            ],
            options={
                'verbose_name': 'Équipement',
                'verbose_name_plural': 'Équipements',
            },
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        max_length=100, verbose_name='Nom de la prodécure'
                    ),
                ),
                (
                    'price',
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name='Prix (CHF)'
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Salles',
                'verbose_name_plural': 'Salles',
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=50, verbose_name='Type de salle')),
            ],
            options={
                'verbose_name': 'Type de salle',
                'verbose_name_plural': 'Types de salle',
            },
        ),
        migrations.CreateModel(
            name='Appointement',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                (
                    'animal',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='appointement',
                        to='animal.animal',
                        verbose_name='Animal',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Consultation',
                'verbose_name_plural': 'Consultations',
            },
        ),
    ]
