# Generated by Django 6.0 on 2025-12-16 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointement', '0001_initial'),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointement',
            name='employee',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='appointement',
                to='employee.employee',
                verbose_name='Employé',
            ),
        ),
        migrations.AddField(
            model_name='appointementequipement',
            name='appointement',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to='appointement.appointement',
                verbose_name='Consultation',
            ),
        ),
        migrations.AddField(
            model_name='appointementprocedure',
            name='appointement',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to='appointement.appointement',
                verbose_name='Consultation',
            ),
        ),
        migrations.AddField(
            model_name='appointement',
            name='emergency_type',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='appointement',
                to='appointement.emergencytype',
                verbose_name='Type de consultation',
            ),
        ),
        migrations.AddField(
            model_name='appointementprocedure',
            name='prodecure',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to='appointement.procedure',
                verbose_name='Procédure',
            ),
        ),
        migrations.AddField(
            model_name='appointementequipement',
            name='equipement',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to='appointement.procedure',
                verbose_name='Équipement',
            ),
        ),
        migrations.AddField(
            model_name='appointement',
            name='room',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='appointement',
                to='appointement.room',
                verbose_name='Salle',
            ),
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='room',
                to='appointement.roomtype',
                verbose_name='Type de salle',
            ),
        ),
    ]
