# Generated by Django 6.0 on 2025-12-16 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointement', '0002_initial'),
        ('employee', '0002_alter_disponibilityrange_options_and_more'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='procedure',
            options={'verbose_name': 'Procédure', 'verbose_name_plural': 'Procédures'},
        ),
        migrations.CreateModel(
            name='AppointementItem',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('quantity', models.IntegerField()),
                (
                    'appointement',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to='appointement.appointement',
                        verbose_name='Consultation',
                    ),
                ),
                (
                    'item',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to='inventory.item',
                        verbose_name='Article',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Association consultation/article',
                'verbose_name_plural': 'Associations consultation/article',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'content',
                    models.TextField(max_length=500, verbose_name='Contenu de la note'),
                ),
                ('created_at', models.DateTimeField(verbose_name='Date de création')),
                (
                    'appointement',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='notes',
                        to='appointement.appointement',
                        verbose_name='Consultation',
                    ),
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='notes',
                        to='employee.employee',
                        verbose_name='Créé par',
                    ),
                ),
                (
                    'valided_by',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='validated_notes',
                        to='employee.employee',
                        verbose_name='Validé par',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
            },
        ),
    ]
