# Generated by Django 6.0 on 2025-12-18 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
        ('family', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(max_length=50, verbose_name="Nom de l'animal"),
                ),
                ('birthday', models.DateField()),
                (
                    'federal_identification',
                    models.CharField(
                        max_length=100, verbose_name='Identification fédérale'
                    ),
                ),
                (
                    'family',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='animal',
                        to='family.family',
                        verbose_name='Contact',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animaux',
            },
        ),
        migrations.CreateModel(
            name='SOAPNote',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'content',
                    models.TextField(
                        max_length=500, verbose_name='Contenu de la SOAP note'
                    ),
                ),
                ('created_at', models.DateTimeField(verbose_name='Date de création')),
                ('text_subjective', models.TextField(verbose_name='Texte subjectif')),
                ('text_objective', models.TextField(verbose_name='Texte objectif')),
                (
                    'text_assessment',
                    models.TextField(verbose_name="Texte d'évaluation"),
                ),
                ('text_plan', models.TextField(verbose_name='Texte de planification')),
                (
                    'animal',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='notes',
                        to='animal.animal',
                        verbose_name='Animal',
                    ),
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='created_notes',
                        to='employee.employee',
                        verbose_name='Créé par',
                    ),
                ),
                (
                    'validated_by',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='validated_notes',
                        to='employee.employee',
                        verbose_name='Validé par',
                    ),
                ),
            ],
            options={
                'verbose_name': 'SOAP Note',
                'verbose_name_plural': 'SOAP Notes',
            },
        ),
    ]
