# Generated by Django 6.0 on 2025-12-16 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('family', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(max_length=50, verbose_name="Nom de l'animal"),
                ),
                ('birthday', models.DateField()),
                (
                    'federal_identification',
                    models.CharField(
                        max_length=100, verbose_name='Identification fédérale'
                    ),
                ),
                (
                    'family',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='animal',
                        to='family.family',
                        verbose_name='Contact',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animaux',
            },
        ),
        migrations.CreateModel(
            name='AnimalChart',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'animal',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='animal_chart',
                        to='animal.animal',
                        verbose_name='Animal',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Dossiers médicaux',
            },
        ),
    ]
