# Generated by Django 6.0 on 2025-12-31 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soapnote',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True, verbose_name='Date de création'
            ),
        ),
    ]
