# Generated by Django 6.0 on 2026-01-03 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0002_alter_soapnote_created_at'),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soapnote',
            name='validated_by',
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='validated_notes',
                to='employee.employee',
                verbose_name='Validé par',
            ),
        ),
    ]
