# Generated by Django 6.0 on 2026-01-08 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0002_alter_soapnote_created_at'),
    ]

    def create_default_species(apps, schema_editor):
        Species = apps.get_model('animal', 'Species')
        Species.objects.create(name='Chien')

    def delete_default_species(apps, schema_editor):
        Species = apps.get_model('animal', 'Species')
        Species.objects.filter(name='Chien').delete()

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(max_length=50, verbose_name="Nom de l'espèce"),
                ),
            ],
            options={
                'verbose_name': 'Espèce',
                'verbose_name_plural': 'Espèces',
            },
        ),
        migrations.AddField(
            model_name='animal',
            name='death_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RunPython(create_default_species, delete_default_species),
    ]
