# Generated by Django 6.0 on 2026-01-08 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0003_species_animal_death_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='species',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='animals',
                to='animal.species',
                verbose_name='Espèce',
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='species',
            name='name',
            field=models.CharField(
                max_length=50, unique=True, verbose_name="Nom de l'espèce"
            ),
        ),
    ]
