# Generated by Django 6.0 on 2026-01-10 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0004_alter_soapnote_validated_by'),
        ('animal', '0004_animal_species_alter_species_name'),
    ]

    operations = []
