# Generated by Django 6.0 on 2025-12-18 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('phone', models.IntegerField(verbose_name='Numéro de téléphone')),
                ('email', models.CharField(max_length=255)),
                ('birthday', models.DateField(verbose_name='Date de naissance')),
                ('password_hash', models.CharField(verbose_name='Mot de passe')),
            ],
            options={
                'verbose_name': 'Personne',
                'verbose_name_plural': 'Personnes',
            },
        ),
    ]
