# Generated by Django 6.0 on 2025-12-30 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='password_hash',
            field=models.CharField(max_length=128, verbose_name='Mot de passe'),
        ),
    ]
