# Generated by Django 6.0 on 2026-01-09 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_person_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='password_hash',
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name='Mot de passe'
            ),
        ),
    ]
