# Generated by Django 6.0 on 2026-01-11 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0004_alter_person_password_hash'),
        ('person', '0004_person_user'),
    ]

    operations = []
