# Generated by Django 6.0 on 2025-12-16 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisponibilityRange',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        max_length=100, verbose_name="Fonction de l'employé(e)"
                    ),
                ),
            ],
            options={
                'verbose_name': "Fonctions de l'employé(e)",
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('first_engagement_date', models.DateField()),
                (
                    'person',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='employee',
                        to='person.person',
                        verbose_name='Personne',
                    ),
                ),
                (
                    'role',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='employee',
                        to='employee.role',
                        verbose_name="Fonction de l'employé(e)",
                    ),
                ),
            ],
            options={
                'verbose_name': 'Employés(es)',
            },
        ),
        migrations.CreateModel(
            name='DisponibilityEmployee',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'disponibility_range',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='employee.disponibilityrange',
                        verbose_name='Période',
                    ),
                ),
                (
                    'employee',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='employee.employee',
                        verbose_name='Employé(e)',
                    ),
                ),
            ],
        ),
    ]
