# Generated by Django 6.0 on 2025-12-16 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disponibilityrange',
            options={
                'verbose_name': 'Période de disponibilité',
                'verbose_name_plural': 'Périodes de disponibilité',
            },
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={
                'verbose_name': 'Employé(e)',
                'verbose_name_plural': 'Employé(e)s',
            },
        ),
        migrations.AlterModelOptions(
            name='role',
            options={
                'verbose_name': "Fonction de l'employé(e)",
                'verbose_name_plural': "Fonctions de l'employé(e)",
            },
        ),
    ]
