# Generated by Django 6.0 on 2026-01-11 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_openexception_openhours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabilityemployee',
            name='day_of_week',
            field=models.IntegerField(
                choices=[
                    (0, 'Lundi'),
                    (1, 'Mardi'),
                    (2, 'Mercredi'),
                    (3, 'Jeudi'),
                    (4, 'Vendredi'),
                    (5, 'Samedi'),
                    (6, 'Dimanche'),
                ]
            ),
        ),
        migrations.AlterField(
            model_name='openhours',
            name='day_of_week',
            field=models.IntegerField(
                choices=[
                    (0, 'Lundi'),
                    (1, 'Mardi'),
                    (2, 'Mercredi'),
                    (3, 'Jeudi'),
                    (4, 'Vendredi'),
                    (5, 'Samedi'),
                    (6, 'Dimanche'),
                ]
            ),
        ),
    ]
