# Generated by Django 6.0 on 2026-01-10 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_alter_activitylog_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylog',
            name='object_name',
        ),
        migrations.AddField(
            model_name='activitylog',
            name='object_id',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
    ]
